name: Android CI
permissions:
  contents: read
  
on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Set up auth config
      env:
        AUTH_CONFIG: ${{secrets.AUTH_CONFIG}}
      run:
        echo "$AUTH_CONFIG" > app/src/main/res/raw/auth_config_apk.json
    - name: Decode keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        STRORE_FILE: ${{secrets.STRORE_FILE}}
      run: echo "$KEYSTORE_BASE64" | base64 --decode > app/debug-key.jks
    - name: Set up keystore Debug
      env:
          KEY_ALIAS: ${{secrets.KEY_ALIAS}}
          KEY_PASSWORD: ${{secrets.KEY_PASSWORD}}
          STORE_PASSWORD: ${{secrets.STORE_PASSWORD}}
      run: |
          echo "keyAlias=$KEY_ALIAS" > keystore.properties
          echo "keyPassword=$KEY_PASSWORD" >> keystore.properties
          echo "storePassword=$STORE_PASSWORD" >> keystore.properties
          echo "storeFile=debug-key.jks" >> keystore.properties
    - name: Set up keystore Release
      env:
        KEY_ALIAS: ${{secrets.KEY_ALIAS}}
        KEY_PASSWORD: ${{secrets.KEY_PASSWORD}}
        STORE_PASSWORD: ${{secrets.STORE_PASSWORD}}
      run: |
        echo "keyAlias=$KEY_ALIAS" > keystore.properties.release
        echo "keyPassword=$KEY_PASSWORD" >> keystore.properties.release
        echo "storePassword=$STORE_PASSWORD" >> keystore.properties.release
        echo "storeFile=debug-key.jks" >> keystore.properties.release
    - name: Set up env
      env:
          MSAL_HOST: ${{secrets.MSAL_HOST}}
          MSAL_PATH: ${{secrets.MSAL_PATH}}
      run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "MSAL_HOST=$MSAL_HOST" >> local.properties
          echo "MSAL_PATH=$MSAL_PATH" >> local.properties
    - name: Build with Gradle
      run: ./gradlew build
