name: Android CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Make dir
      run: mkdir app/src/main/res/raw
    - name: Set up auth config
      env:
        AUTH_CONFIG: ${{secrets.AUTH_CONFIG}}
      run:
        echo "$AUTH_CONFIG" > app/src/main/res/raw/auth_config_single_account.json
    - name: Set up env
      env:
          MSAL_HOST: ${{secrets.MSAL_HOST}}
          MSAL_PATH: ${{secrets.MSAL_PATH}}
      run: |
          echo "MSAL_HOST=$MSAL_HOST" >> local.properties
          echo "MSAL_PATH=$MSAL_PATH" >> local.properties
    - name: Build with Gradle
      run: ./gradlew build
